apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  # ye deployement ke liye hai
  replicas: 3
  selector:
    matchLabels:
      app: second-app
      tier: backend
  template:
  # ye pods ke liye hai
    metadata:
      labels:
        app: second-app
        tier: backend
    spec:
      # spec of individual pods
      containers:
        - name: second-node
          image: pavankumar07s/kube_first_app:2
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          # - name: ...
          #   image: ...
          ports:
            - containerPort: 80
